<?php

namespace App\Http\Controllers\WEB\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\TranslateLangMessage;
use App\Models\Language;
use App\Models\LangMessage;
class FontendLanguageController extends Controller
{
    public function index($langCode)
    {
        $lang_massage = LangMessage::first();
        $translate_lang_massage =  TranslateLangMessage::where('message_id',$lang_massage->id)->where('lang_code',$langCode)->first();
        $selected_language = Language::where('lang_code',$langCode)->select('name')->first();
        $inputVariables = [
            'see_more',
            'add_to_cart',
            'read_more',
            'all_category',
            'off',
            'success',
            'event',
            'google_play',
            'i_store',
            'about_us',
            'home',
            'years',
            'most_popular_items',
            'blog',
            'blog_details',
            'tag',
            'share',
            'comments',
            'leave_a_comment',
            'required_fields_are_marked',
            'submit_now',
            'search',
            'latest_blog',
            'follow_us',
            'shopping_cart',
            'image',
            'details',
            'price',
            'quantity',
            'total',
            'action',
            'addons',
            'view',
            'select_addon',
            'optional',
            'select_size',
            'select_quantity',
            'update_cart',
            'process_to_checkout',
            'select_addresses',
            'add_new',
            'add_new_address',
            'back',
            'first_name',
            'last_name',
            'phone',
            'email',
            'country',
            'select_country',
            'state',
            'select_state',
            'city',
            'select_city',
            'address',
            'office',
            'save_now',
            'perfect_time_for_delivery',
            'today',
            'tomorrow',
            'time_schedule',
            'select_time_schedule',
            'cart_summary',
            'delivery',
            'pick_up',
            'in_restaurant',
            'apply_coupon',
            'apply',
            'subtotal',
            'discount',
            'delivery_charges',
            'grand_total',
            'process_order',
            'contact_us',
            'name',
            'email2',
            'telephone',
            'subject',
            'message',
            'send_now',
            'call_restaurant',
            'number_of_guest',
            'select_guest',
            'stars',
            'food_details',
            'Food_video',
            'review',
            'sent_review',
            'remove',
            'wishlist',
            'menu',
            'my_cart',
            'sign_up',
            'login',
            'select_category',
            'size',
            'vat',
        ];
        
        return view('Admin.FontendLanguage',compact('translate_lang_massage','selected_language','inputVariables'));
    }

    public function update(Request $request ,$id)
    {
        $inputKeys  = [
            'see_more',
            'add_to_cart',
            'read_more',
            'all_category',
            'off',
            'success',
            'event',
            'google_play',
            'i_store',
            'about_us',
            'home',
            'years',
            'most_popular_items',
            'blog',
            'blog_details',
            'tag',
            'share',
            'comments',
            'leave_a_comment',
            'required_fields_are_marked',
            'submit_now',
            'search',
            'latest_blog',
            'follow_us',
            'shopping_cart',
            'image',
            'details',
            'price',
            'quantity',
            'total',
            'action',
            'addons',
            'view',
            'select_addon',
            'optional',
            'select_size',
            'select_quantity',
            'update_cart',
            'process_to_checkout',
            'select_addresses',
            'add_new',
            'add_new_address',
            'back',
            'first_name',
            'last_name',
            'phone',
            'email',
            'country',
            'select_country',
            'state',
            'select_state',
            'city',
            'select_city',
            'address',
            'office',
            'save_now',
            'perfect_time_for_delivery',
            'today',
            'tomorrow',
            'time_schedule',
            'select_time_schedule',
            'cart_summary',
            'delivery',
            'pick_up',
            'in_restaurant',
            'apply_coupon',
            'apply',
            'subtotal',
            'discount',
            'delivery_charges',
            'grand_total',
            'process_order',
            'contact_us',
            'name',
            'email2',
            'telephone',
            'subject',
            'message',
            'send_now',
            'call_restaurant',
            'number_of_guest',
            'select_guest',
            'stars',
            'food_details',
            'Food_video',
            'review',
            'sent_review',
            'remove',
            'wishlist',
            'menu',
            'my_cart',
            'sign_up',
            'login',
            'select_category',
            'size',
            'vat',
        ];
        
        $tr = TranslateLangMessage::find($id);
        foreach ($inputKeys as $key) {
            $tr->$key = $request->input($key);
        }
        $tr->save();
        $message = "Update Successfully!!";
        $notification = array('message'=> $message,'alert-type' => 'success');
        return redirect()->back()->with($notification);
    }
}
